force-app/main/default/objects/Change_History_Config__c/Change_History_Config__c.object-meta.xml
<CustomObject>
    <label>Change History Config</label>
    <nameField>
        <displayFormat>CHC-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change History Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Change_History_Config__c/fields/Object_Api__c.field-meta.xml
<CustomField>
    <fullName>Object_Api__c</fullName>
    <label>Object Api</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Change_History_Config__c/fields/Tracked_Fields__c.field-meta.xml
<CustomField>
    <fullName>Tracked_Fields__c</fullName>
    <label>Tracked Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Change_History_Configuration__mdt/Change_History_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Change History Configuration</label>
    <pluralLabel>Change History Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Change_History_Configuration__mdt/fields/Object_API__c.field-meta.xml
<CustomField>
    <fullName>Object_API__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Object API</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Change_History_Configuration__mdt/fields/Tracked_Fields__c.field-meta.xml
<CustomField>
    <fullName>Tracked_Fields__c</fullName>
    <label>Tracked Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ChangeHistroySetupUtil.cls
public with sharing class ChangeHistroySetupUtil {
  public static Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();

  private final static Set<String> UNSUPPORTED_STANDARD_OBJECTS = new Set<String>{
    'AccountFeed',
    'AccountPartner',
    'AccountShare',
    'ActivityHistory',
    'CaseComment',
    'CollaborationGroup',
    'ContentVersion',
    'Document',
    'EntitySubscription',
    'FeedComment',
    'FeedItem',
    'Group',
    'Idea',
    'IdeaComment',
    'NewsFeed',
    'NoteAndAttachment',
    'Partner',
    'PermissionSet',
    'ProcessInstance',
    'ProcessInstanceHistory',
    'Solution',
    'Topic',
    'User',
    'UserProfileFeed',
    'UserRole'
  };

  private final static Set<String> UNSUPPORTED_CUSTOM_OBJECTS = new Set<String>{
    'Change_History_Config__c'
  };

  public static Set<String> retrieveUnsupportedObjects() {
    Set<String> unsupported = new Set<String>();

    unsupported.addAll(UNSUPPORTED_STANDARD_OBJECTS);
    unsupported.addAll(UNSUPPORTED_CUSTOM_OBJECTS);

    return unsupported;
  }

  public static Map<String, Schema.SObjectField> getFieldsDescribe(
    String selectedObject
  ) {
    return schemaMap.get(selectedObject).getDescribe().fields.getMap();
  }

  public static String getConfigurationByObjectApi(String selectedObject) {
    //fetch mdt
    if (
      !Schema.sObjectType.Change_History_Configuration__mdt.fields.Tracked_Fields__c.isAccessible()
    ) {
      return '';
    }
    String objConfig = '';
    List<Change_History_Configuration__mdt> configList = [
      SELECT id, Tracked_Fields__c
      FROM Change_History_Configuration__mdt
      WHERE Object_API__c = :selectedObject
    ];
    if(configList.size()>0){
      objConfig = configList.get(0).Tracked_Fields__c;
    }
    return objConfig;
  }
  
}